<?php

namespace MVC;

require_once dirname(__FILE__) . '/../Source/Route.php';

/**
 * Test class for Route.
 * Generated by PHPUnit on 2011-06-03 at 13:39:56.
 */
class RouteTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Route
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @todo Implement testGetDefaultValue().
     */
    public function testGetDefaultValue() {
        $this->object = new Route("{controller}/{action}.php?param1={param1}&param2={param2}", 
                array("{controller}" => "Home", "{action}" => "Index", "{param1}" => 3));
    }

    /**
     * @todo Implement testGetTypeConstrains().
     */
    public function testGetTypeConstrains() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
